[versions]
kotlin = "2.3.21"
spring-boot = "4.1.0"
spring-dependency-management = "1.1.7"
guice = "7.0.0"
guava = "33.6.0-jre"
junit-jupiter = "6.0.3"
#mockito-junit-jupiter = "5.23.0"
#mockito-core = "5.23.0"
mockito = "5.23.0"

[libraries]
guice = { module = "com.google.inject:guice", version.ref = "guice" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
#mockito-junit-jupitor = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito-junit-jupiter" }
#mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-core" }
mockito-junit-jupitor = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }

[bundles]
mockito = ["mockito-junit-jupitor", "mockito-core"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }

